# Originally coded by David Belanger for ocean colour bloom metrics study in 2023-2024.

library(ggplot2)
library(ggh4x)
library(ggpubr)
library(patchwork)
library(dplyr)

# dat_file <- "analysis/satelliteOceanColour/data/verified_fits_labrador_sea_fall.Rdata" # Rdata file generated by format_bloommetrics script in PhytoFit "tools"
# bounds_file <- "analysis/satelliteOceanColour/data/labrador_sea_polygon_season_bounds.csv" # columns: Region, spring/summer/fall
# output_file <- "analysis/satelliteOceanColour/figures/AZOMP_polygon_season_bounds_OCCCI.png"
# years <- 1999:2020 # climatological period

dat_file <- "analysis/satelliteOceanColour/data/verified_fits_labrador_sea_spring_linear_modisaqua.Rdata" # Rdata file generated by format_bloommetrics script in PhytoFit "tools"
bounds_file <- "analysis/satelliteOceanColour/data/labrador_sea_modisaqua_polygon_season_bounds.csv" # columns: Region, spring/summer/fall
output_file <- "analysis/satelliteOceanColour/figures/AZOMP_polygon_season_bounds_MODIS.png"
years <- 2003:2020 # climatological period

poly_abbrevs <- c("LAS","CLS","GS")
poly_names <- c("Hamilton Bank","Central Labrador Sea","Greenland Shelf")


#*******************************************************************************

#plotting x-axis breaks and labels
x.ticks <- c(1, 32, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335, 365)
x.month <- c(15.5, 46, 76.5, 106, 136.5 ,167, 197.5, 228.5, 259, 289.5, 320, 350)
x.labs <- c("J","F","M","A","M","J","J","A","S","O","N","D")

dat <- get(load(dat_file)) %>% dplyr::select(Region,Year,stats) %>% tidyr::unnest(col=stats) %>% dplyr::select(Region,Year,doy,mean,percent_coverage)
dat$goodcov <- ifelse(dat$percent_coverage>=20,TRUE,FALSE)


# # temporary for modis fits!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# dat <- dat %>% dplyr::mutate(mean=10^mean)


# get the seasonal boundaries
bounds <- read.csv(bounds_file)
bp <- lapply(poly_abbrevs, function(x) {
    bounds %>% dplyr::filter(Region==x) %>% dplyr::select(-Region) %>% unlist() %>% round()
}) %>% setNames(poly_abbrevs)

lims <- range(dat$mean,na.rm=TRUE)

plots <- lapply(1:length(poly_abbrevs), function(i) {
    poly_abbrev <- poly_abbrevs[i]
    poly_name <- poly_names[i]
    dat_poly <- dat %>% filter(Year%in%years & Region==poly_abbrev)
    ggplot(dat_poly %>% dplyr::mutate(Year=factor(Year)), aes(x=doy, y=mean))+
        geom_rect(xmin=bp[[poly_abbrev]][1],xmax=bp[[poly_abbrev]][2],aes(ymin=lims[1],ymax=lims[2]),fill="#dddddd") +
        geom_rect(xmin=bp[[poly_abbrev]][3],xmax=365,aes(ymin=lims[1],ymax=lims[2]),fill="#dddddd") +
        geom_point(aes(color=goodcov,alpha=goodcov), size=1, pch=16)+
        scale_color_manual(values=c("black","red"),breaks=c(TRUE,FALSE)) +
        scale_alpha_manual(values=c(0.9,0.4),breaks=c(TRUE,FALSE)) +
        stat_smooth(method="loess", span=0.2, size=.75, col="black", se=T)+
        scale_x_continuous(expand=c(0,0), limits=c(1,365), breaks=x.month, labels=x.labs,
                           guide="axis_minor", minor_breaks=x.ticks)+
        scale_y_log10(expand=c(0,0), limits=lims)+
        labs(title=poly_name, 
             x="DOY", 
             y=expression(Log[10]~(chl~italic(a))))+
        theme(panel.background=element_rect(fill=NA, color="Black"),
              panel.border=element_rect(fill=NA,color="black"),
              axis.ticks.length.x=unit(.1, "mm"),
              axis.title=element_blank(),
              ggh4x.axis.ticks.length.minor=rel(25),
              plot.title=element_text(size=20),
              axis.text=element_text(size=14),
              legend.position="none")
})
plots[2:length(plots)] <- lapply(plots[2:length(plots)], function(x) {x+theme(axis.text.y=element_blank())})
p <- wrap_plots(plots,nrow=1)

ggsave(filename=output_file, plot=p, height=600, width=2000, dpi=150, units="px")
