# Results and Discussion

## Total inorganic carbon and pH

The Labrador Sea hosts a strong “solubility pump”—atmospheric anthropogenic $CO_2$ is sequestrated to the deep ocean by chemical and physical processes. The depth of the Newly Ventilated Labrador Sea Water (NV-LSW) trapped by winter convection varies from year to year, ranging from 500 m to over 2000 m. The average concentrations of TIC and pH, between 150 and 500 m for stations from 56$\degree$N to 59.1$\degree$N (within the Central Labrador Sea), were used as representative concentrations for NV-LSW and suffered relatively less from seasonal variability. TIC concentration increased by  0.78 $\mu~mol~kg^{-1}~y^{-1}$ from 1996 to 2023, reaching a maximum of 2167.92 $\mu~mol~kg^{-1}$ in 2022 in response to the local uptake of anthropogenic $CO_2$ (Figure \@ref(fig:TICpH)). As a result, the pH decreased by 0. 0.09 units during the same period (Figure \@ref(fig:TICpH)) representing a decline rate of 0.003 $y^{-1}$. Trends between 1996 and 2023 were highly significant with a correlation coefficient, $r^{2}$, explaining respectively 97% and 84% of the variance in TIC and pH. Arctic outflow and the local uptake of anthropogenic $CO_2$ in the deep-convection region of the Labrador Sea are major controlling mechanisms for the state of ocean acidification in the northwest Atlantic, and the continuous trend observed in our dataset could impact this entire region. The Arctic water inflows to the highly productive regions in the northwest Atlantic, which have important commercial fisheries and make these regions more susceptible to future ocean acidification than other regions [@azetsuscott10]. Ocean acidification also influences the capacity of the ocean to take up $CO_2$ from the atmosphere.  

## Transient tracers CFC-12 and $SF_6$

During the second half of the twentieth century, the atmospheric burden of CFCs increased steadily, due mainly to their widespread use as refrigerants and aerosol propellants. The invasive atmospheric flux of these mostly inert gases provided an excellent record of ocean circulation, and profiles of dissolved CFC-12 concentration have been measured annually along the AR7W line since 1991 (Figure \@ref(fig:CFC12SF6)). As a consequence of restrictions on the manufacturing and use of ozone-depleting substances introduced in 1989, the atmospheric mixing ratio of CFC-12 has been in decline since 2003 and its capacity at tracking recent ventilation episodes has become limited (Figure \@ref(fig:CFC12SF6)). Measurements of an alternative transient tracer, $SF_6$, were introduced in 2011. There has been a rapid, near-linear increase in atmospheric $SF_6$ since 2011 and it is reflected in the dissolved concentration profiles of the recently ventilated water, represented by the layer of the Central Labrador Sea between 150 and 500m (Figure \@ref(fig:CFC12SF6)), compared with CFC-12.  

## Temperature in the top 100m

Temperatures recorded by the CTD during the occupation were averaged between 0 and 100 m, which corresponds roughly to the temperature regime of the phyto- and mesozoo- plankton sample layer. Because the timing of the cruise affects the average temperature for a given region and year, removal of the 2003 and 2004 (due to later-than-usual sampling dates, Figure \@ref(fig:cruisebloomdates)) from the reference period lowered it by about 0.2 $\degree$C with little effect on the anomaly patterns (not shown here). HB exhibited a lower temperature (mean of 0.8 $\degree$C) than the CLS (mean of 3.8 $\degree$C) and the GS (mean of 2.3 $\degree$C) due to the inflow of Arctic water (Figure \@ref(fig:scorecardtemperature)).  

The CLS warmest year occurred in 2000 (+1.67 standard deviations from the mean, unitless), while the warmest anomaly for the GS happened in 2008 (+1.92) (Figure \@ref(fig:scorecardtemperature)). The coolest year on the HB occurred in 1996 (-2.12) and in 2018 on the CLS (-1.51). The HB and CLS show year-to-year variability between 2019 and 2023 with 2019 being the warmest recorded anomaly in the CLS (+1.47). The GS showed negative anomalies in 2022 and 2023, a trend that started in 2011 (except 2019), perhaps with less intensity in recent years. In 2023, both shelves exhibited temperature slightly lower than normal, while the CLS showed temperature higher than normal. Unfortunately, the lack of data in 2020, and a late mission in 2021, did not allow confirmation of these trends.  

## Nutrients

All near-surface nutrient concentrations (i.e., 0–100 m, nitrate, phosphate, and silicate) exhibited inter-annual variations between 1997 and 2010, followed by three years (2011 to 2013) of below average nutrient levels  for all regions except the silicate concentration in 2011 on HB (Figure \@ref(fig:scorecardnutrientsshallow)). From 2014 to 2018, all nutrients levels were above normal except for nitrate and phosphate in 2015 in CLS. While no patterns are observed between nutrients and regions before 2011, all regions and nutrients anomalies were correlated between 2011 and 2019.  

Since 2019, surface nitrates show negative trends in all three regions, except on the Greenland Shelf in 2022 (Figure \@ref(fig:scorecardnutrientsshallow)). The same year, a record-low in nitrate was measured in the CLS. The same trends were observed in phosphate anomalies between 2019 and 2023 with lower than usual concentrations in both the HB and CLS, and a record low phosphate in the CLS in 2023. Silicate levels show a different pattern with more variability than nitrate and phosphate levels. HB showed lower than normal silicate levels since 2019 with a record low in 2022. Silicate levels were close to normal in the CLS. In 2019, silicate were lower than normal on the GS and higher than normal in 2022 and 2023.  

Deep nutrients (100+ m to bottom) showed a different pattern than the surface nutrients in agreement with the hydrodynamics of the Labrador Sea and the surface-layer biological activity (Figure \@ref(fig:scorecardnutrientsdeep)). Deep nutrients levels are less impacted by the timing of the mission as they are not consumed by phytoplankton and microbial remineralization at depth replenishes the nutrient pool.  Deep nutrients anomalies showed large interannual variability between 1999 and 2018 (Figure \@ref(fig:scorecardnutrientsdeep)), interestingly most of the record-high levels occurred in the first half of the time series, except for nitrate and silicate on HB, which occurred in 2015, a notable year given an unusual large bloom of Phaeocystis sp [@devred24]. On the other hand, record-low levels of nutrients occurred after 2009. While no clear trend has emerged for the scorecards, since 2019 all deep nutrients have showed below-average levels. However, This trend should be interpreted with caution given that no data from 2020 and 2021 are included. It is noteworthy that these below-average levels of nutrients that started in 2019 coincided with the trend for surface nutrients (Figures \@ref(fig:scorecardnutrientsshallow) and \@ref(fig:scorecardnutrientsdeep)).  

## In situ chlorophyll-a concentration

In general, the GS region has high levels of integrated chl-a with a mean of 380 $mg~m^{-2}$ (Figure \@ref(fig:scorecardchla)), and is dominated by nanophytoplankton with low concentrations of picophytoplankton. Conversely, the CLS is a region with low integrated chl-a (165 $mg~m^{-2}$) and a low proportion of nanophytoplankton, with high concentrations of picophytoplankton. The HB region exhibits the lowest concentrations of integrated chl-a (122 $mg~m^{-2}$) and micro- and nano-phytoplankton dominates the phytoplankton assemblage, with low biomass of picophytoplankton. Upper ocean (< 100 m depth) phytoplankton sampled on the AR7W section in spring and early summer between 1999 and 2022 showed region-specific characteristics [@li14, @fragoso16, @devred24].  

Integrated chl-a shows a low frequency variability with a given trend (above or below average) that remains for several years at a time. In that respect, the time series for the HB and CLS show two periods of lower-than-normal levels, from about 2001 to 2005 and from 2014 to 2019, while the remaining periods show above-normal values. Record-high level of integrated chl-a occurred in 2022 (+3.48) on the HB and in 2015 in the CLS. Note that both years corresponds to very large blooms of Phaeocystis sp. The GS showed a different pattern than the two other regions, with lower than normal values between 2001 and 2008, followed by a period of large interannual variability (2009 to 2013, 2009 being the record high). Since 2014, integrated chl-a has been lower than average.  

Regarding the period of interest in the current report, 2019 to 2023, integrated chl-a showed lower than normal levels in 2019 in all three regions, continuing a trend that started in 2014 (except in Central Labrador Sea in 2015, Figure \@ref(fig:scorecardchla)). This trend was also observed in 2022 and 2023 on the Greenland Shelf, although the integrated chl-a was close to normal in 2023. The HB and CLS showed higher than normal levels in 2022 and 2023, with a record high value in 2022 on the CLS.  

Integrated chl-a levels do not necessarily agree with nutrients concentrations, which can be somewhat explained by the timing of the missions (Figure \@ref(fig:cruisebloomdates)). For instance, in 2013, the mission sampled the transect at the peak of the bloom (as indicated by satellite ocean colour), resulting in high integrated chl-a and low nutrients, likely depleted by phytoplankton consumption. Conversely, in 2014, the mission sampled the AR7W before or at the start of the spring bloom, when chl-a concentration was low and nutrients levels high. Similarly, both 2021 and 2022 missions on HB and in the CLS occurred at the peak of the spring bloom (Figure \@ref(fig:cruisebloomdates)), corresponding to high integrated chl-a values and low nutrients values.  

## Satellite-derived chlorophyll-a and bloom indices

Satellite-derived chl-a allows observation of the Labrador Sea all year long, but is limited by sea-ice and cloud cover. The main advantage of the satellite is that information on phytoplankton biomass can be reported when sea-going missions have been cancelled. Here we report on the timing of the spring and fall blooms, and annual and seasonal mean chl-a in the three regions of interest.  

The timing of the spring bloom is highly variable and depends on several factors, including the thermal stratification, the amount of nutrients, the light available for photosynthesis and the grazing pressure. The spring bloom generally occurs first on the GS (day of year (doy) 135 on average), then on the HB (doy 153 on average) and shortly after in the CLS (doy 160 on average). There are no long term trends observed in the timing of the spring bloom but rather a strong interannual variability. Following the record-late spring initiation in 2018 on HB, both 2019 and 2020 also showed a late bloom, while 2021, 2022 and 2023 showed an earlier than normal bloom initiation. In the CLS, the bloom initiation was late from 2019 to 2021, the later year exhibiting the record-late bloom, which was followed by a record-early bloom in 2022. Note that in 2022, a very large and unusual bloom of Phaeocystis sp. was observed [@devred24]. In 2023, the spring bloom initiation occurred later than normal. In fact, the 2022 bloom was the only one observed to occur earlier than normal since 2016. On the GS, both 2019 and 2021 showed earlier than normal bloom initiation, while it was later than normal for the other years. The spring bloom in 2023 was the record-late timing on the GS. A secondary bloom occurs in the Fall, less intense than the spring one, triggered by the replenishment in nutrients of the surface-lit layer by storm-induced vertical mixing when light is still sufficient to stimulate phytoplankton productivity. Similar to the spring bloom peak timing, the fall bloom initiation is very variable over the time series and for each region. Overall, the fall bloom timing has been earlier than normal since 2012, except for a few late years in each regions. On HB, the bloom was earlier than normal in 2019, 2020 and 2021, while it was later than normal in 2022, but exhibiting a record early timing in 2023. In the CLS, the fall bloom occurred earlier than usual in all years, however no fall bloom was observed in 2021. On the GS, the fall bloom timing showed a similar pattern to HB, with an extremely late fall bloom (anomaly of 1.42).  

Annual and spring anomalies show correlation in all three regions, suggesting that the spring bloom drives the annual production. The mean annual and seasonal chl-a shows a high interannual variability. Examining the anomalies in recent years (2019 to 2023), HB exhibited a record high annual chl-a average (+2.03) despite lower than average levels of nitrate and silicate, suggesting that the ecosystem is not nutrient-limited. The mean annual chl-a was above average in all three regions in 2023 in spring. CLS showed above normal chl-a in 2022, in particular in spring, due to an anomalously large bloom of Phaeocystis sp. The GS showed the lowest production of the 2019-2023 period in 2020 when mean chl-a was below normal in all seasons except in summer with a relatively high anomaly. In winter, 2022 showed a record-high mean chl-a in the GS. An exceptionally large bloom occurred in 2018 on the HB and CLS (3.92 and 3.97, respectively) impacting the entire reference period and reducing the anomalies for all the other years.  

## Mesozooplankton

Updates from the period currently reported are not yet available, but we have decided to leave the historical sections up to 2019. Calanus finmarchicus copepods dominate the mesozooplankton biomass in the Central Labrador Sea, while it and its congeners C. glacialis and C. hyperboreus contribute about one third each on the shelves [@head03]. C. finmarchicus total abundances are greatly influenced by the abundance of young stage copepodites. These develop from eggs laid by females that have overwintered as pre-adults in the deep central basin and re-ascended in spring. The spring bloom provides the food to fuel egg-laying and subsequent population development, so that regional differences in spring bloom dynamics also lead to differences in the timing of the development of C. finmarchicus populations. Since spring blooms are generally earlier and more intense on the GS than elsewhere, C. finmarchicus populations are generally more abundant there than elsewhere at the time of in situ sampling (Figure 10).  

On the Labrador Shelf, during the 1995 to 2018 period, there were two years with exceptionally high abundances for C. finmarchicus–1999 (June) and 2011 (May)—the reasons for which are unknown (Figure 10). Otherwise, abundances have been variable, with two higher-than-average values (June 2001 and July 2002) and a sustained period of relatively-low abundance between 2004 and 2008. Since 2013, abundances have been slightly below average.  

In the Central Labrador Sea, because the spring bloom and the relatively late development of C. finmarchicus, in situ sampling in summer generally gave higher abundances than in spring, as indicated by the positive anomalies in 1995, 1999, 2002, and 2003 (Figure 10). Young stages were seldom very abundant, perhaps due to high mortality [@head15], except for the summer of 1995, with an exceptionally higher total abundance year. There was no trend in springtime total abundance for C. finmarchicus between 1996 and 2014. Since 2015, however, abundances have been unusually low, perhaps owing to earlier sampling than in previous years (Figures \@ref(fig:cruisebloomdates) and 10).  

On the Greenland Shelf, there was one exceptionally high C. finmarchicus abundance value in May 2006, the cause of which is unclear. Otherwise, higher-than-average values tended to be associated with later sampling dates (e.g., 1995, 1999, 2001–2003, and 2012), while relatively low abundances were associated with early sampling dates since 2012.  

High abundance of C. glacialis and C. hyperboreus on the shelves may result from the transport of individuals in the inflows, since neither species have a local overwintering source population. The abundances of both species have generally shown considerable year-to-year variability, but with sustained periods of low abundance for C. glacialis on both shelves since 2014, and sustained periods of high abundance for C. hyperboreus on the GS between 2009 and 2012 and of low abundance on the LS since 2014. C. hyperboreus abundance on the GS was also low in 2018 (Figure 10).  

Clausocalanidae, mainly represented here by the genius Pseudocalanidae spp, were persistently more abundant than the average in the CLS over the last 10 years, whereas a general decreasing trend was observed on LS and GS since 2014 (Figure 11). Unlike Pseudocalanidae, Oithonidae were persistently less abundant in the Central Labrador Sea for more than 10 years, while the decrease in abundance on both shelves became more prevalent around 2014 (Figure 11). Since 2014, Euphausiid abundances have been consistently lower than average in all regions (Figure 12). Amphipods, mostly represented here by Parathemisto libellula, showed higher-than-average abundances in the Central Labrador Sea in 2018. Being a species associated with Arctic water masses, this phenomenon is consistent with the cooler-than-average temperatures in the Central Labrador Sea during that year (Figure 12).  

