# Introduction {#sec:introduction}

The Labrador Sea is a deep basin nested between Labrador and Greenland with a cyclonic circulation pattern that leads to the mixing of Arctic and North Atlantic waters. The Baffin Island and Labrador currents transport cold and less-saline Arctic water southward along the Canadian coast [@wang16]. On the eastern side, the West Greenland Current brings warmer, more-saline waters northward, along the Greenland coast into the Baffin Bay, where it meets the Labrador Current. (See @lozier19 and @yashayaev17 for a detailed description of the Labrador Sea circulation.) By the end of winter, the cooling of the upper layer results in an increase of surface density, enabling mixing to reach great depths (1500 to 2000 m), thus ventilating the deeper ocean with atmospheric gases while pumping nutrients from the deep waters to the surface. The intensity of this phenomenon varies with environmental factors, including atmospheric forcing, freshwater runoff from adjacent glaciers, precipitation, intrusion of warm and saline inflow from the adjacent North Atlantic, and intrusion of cold and fresh water from the Arctic Ocean. In turn, this deep mixing strongly impacts heat flux, stratification, and by extension, the chemical balance and biological productivity of the Labrador Sea. Consequently, changes in the physical and chemical environment of the aphotic zone influence both plankton community composition and annual biological production cycles, including fish and higher trophic levels.  

About one quarter of the carbon dioxide ($CO_2$) released by human activities is taken up by the global ocean [@sabine04], altering ocean chemistry, and correspondingly, the marine carbonate system. The Labrador Sea hosts a strong “solubility pump”, whereby anthropogenic $CO_2$ sequestrated from the atmosphere is transported to the deep ocean through chemical and physical processes. The dissolution of anthropogenic $CO_2$ has decreased global ocean pH by 0.1 units over the past 200 years, resulting in a 30% increase in acidity globally [@caldeira03]. If global emissions of $CO_2$ remain at their present rate, ocean pH is predicted to drop by an additional 0.3 units by 2100. The oceans have not experienced such a rapid pH decrease (ocean acidification), or one of such a high magnitude, for at least 20 million years [@feely04], raising serious concerns about the ability of marine ecosystems to adapt. The major impact of decreasing pH will be felt by organisms that form calcium carbonate ($CaCO_3$) shells and skeletons, because rising acidity increases the solubility of $CaCO_3$. Since $CaCO_3$ shells and skeletons are naturally more soluble at lower temperatures and higher pressures, high latitudes and deep water ecosystems, such as the one encountered in the Labrador Sea, are more vulnerable to the added stress of ocean acidification than those at intermediate latitudes. Furthermore, rapid environmental changes, such as receding sea-ice extent and enhanced hydrological cycles, may amplify these problems. Inert halogenated trace gases of anthropogenic origin that have accumulated in the atmosphere, such as the chlorofluorocarbons (CFCs) and sulfur hexafluoride ($SF_6$), are used to study ventilation and transport processes in the ocean. In recent decades, they have been used to calculate Transient Tracer Distribution (TTD) to estimate the transit time of water masses and anthropogenic $CO_2$ in the water [@haine02; @hall02].  

Since 1990, as part of the World Ocean Circulation Experiment (WOCE), the Ocean and Ecosystem Sciences Division (OESD) at the Bedford Institute of Oceanography (BIO) has carried out an annual occupation, usually in the spring, of the AR7W (Atlantic Repeat Hydrography Line 7 West) oceanographic section across the Labrador Sea (Figure \@ref(fig:AR7Wmap)). Soon after its inception, the program morphed into Fisheries and Oceans Canada (DFO) Atlantic Zone Off-shelf Monitoring Program (AZOMP), following the OESD’s overarching objectives to: 1) characterize and understand the causes of ocean variability at seasonal, inter-annual, and inter-decadal scales; 2) provide adequate data to monitor the health of the marine ecosystem and support decision-making based on scientific evidence; and 3) to build historical databases to address future issues. The program also contributes to the international Global Climate Observing System (GCOS) and the Climate Variability (CLIVAR) component of the World Climate Research Program (WCRP) and it reports annually with an environmental synopsis to the Northwest Atlantic Fisheries Organization (NAFO).  

The AR7W section spans approximately 900 km across the southern edge of the Labrador Sea, from the Labrador Shelf (near 53$\degree$N) to the Greenland Shelf (near 61$\degree$N) (Figure \@ref(fig:AR7Wmap)). The annual AZOMP multidisciplinary survey of the Labrador Sea primarily consists of AR7W occupations and deployments/recoveries of moorings and Argo floats. The ideal timing of the mission in May aims to capture the fading winter-deep-convection signal and the beginning of the phytoplankton bloom and productivity season, while avoiding possible sea-ice on the Labrador Shelf early in the spring. Sampling the peak of the spring bloom is uncertain given its large inter-annual variability in timing, duration and spatial extent, however, early cruise dates in recent decades have captured its initiation with the exception of the 2020 mission, which occurred in July-August under nutrient-limited conditions (Table \@ref(tab:table1), Figure \@ref(fig:cruisebloomdates)). With nearly three decades of measurements, the time series allows examination of decadal trends in all key ecosystem variables (i.e, temperature, nutrients, plankton biomass and abundance).  

The AR7W transect crosses two productive shelves (Labrador and Greenland Shelves) and the Central Labrador Sea, where phytoplankton production is subject to local forcing (eddies, mixing-stratification) that drive phytoplankton biomass and community structure. In the Central Labrador Sea, light limits primary production for most of the year [@harrison08; @fragoso16], while a shallow mixed layer, and relatively low nitrate concentration, limit phytoplankton growth on the Labrador Shelf following the spring bloom. Phytoplankton growth, in particular diatoms, also seemed to be limited by availability of silicate in the Central Labrador Sea [@harrison08]. These conditions support the emergence of small flagellates such as *Phaeocystis pouchetii* in the northern and eastern region of the Labrador Sea, which can form large blooms under favorable conditions [@fragoso16]. In recent years, large blooms of *Phaeocystis sp.* have also been observed in the western part of the Central Labrador Sea [@devred24]. The Labrador Shelf, influenced by Arctic waters, is dominated by polar diatom species (*Thalassiosira spp.*, *Chaetoceros spp.*,  and *Bacteriosira bathyomphala*) and species associated with sea-ice (*Porosira glacialis* and *Fossula arctica*). Primary production patterns and mesoscale features leave their imprint on the mesozooplankton distribution and abundance [@yebra09]. One species of copepod, *Calanus finmarchicus*, dominates the mesozooplankton biomass throughout the central region of the Labrador Sea, while on the shelves, two Arctic *Calanus* species, *C. glacialis* and *C. hyperboreus*, are equally important [@head03]. *C. finmarchicus* abundance shows regional variations that are generally consistent from year-to-year and are related to differences in the timing of life-cycle events, which are influenced by environmental conditions, including spring bloom dynamics.  

This report describes the biogeochemical state of the Labrador Sea between spring 2019 and spring 2023. Data presented in this report come from: 1) annual surveys carried out over 2-week periods, typically between early May and early June, however, due to the unavailability and subsequent decommissioning of CCGS Hudson,  the timing of the surveys in 2020 occurred in summer between late July and early August and there was no mission in 2021 (Table \@ref(tab:table1)) ; and 2) satellite remote-sensing of daily observations of ocean colour converted into chlorophyll-a (chl-a) concentration.  
