# Summary

The Atlantic Zone Off-Shelf Monitoring Program (AZOMP) provides observations on ocean climate and plankton variability within the Labrador Sea and adjacent shelves affecting ecosystems of Atlantic Canada and climate from a regional to global scale. In the Labrador Sea, surface heat losses in winter result in the formation of dense waters, which spread across the ocean, ventilating the deep layers, thus contributing to the global ocean-overturning circulation.  

Since 2019, average surface temperature in the CLS has fluctuated between anomalously low (2022) and high (2019, 2023) values, whereas the shelves (HB and GS) have been near-normal except for the cold period in 2022. TIC concentrations from the NV-LSW, enclosed within the CLS, have continued to increase as in previous years (0.78 $µmol~kg^{-1}~year^{-1}$ since sampling began in 1996), but at a slower rate (<0.5 $µmol~kg^{-1}~year^{-1}$ post-2019 only). This increase resulted in pH levels continuing their declining trend (0.09 units per year).  



[TRACER SUMMARY HERE]   



Strong inter-annual variability was observed in surface nutrient concentrations, which are consistent among regions. Since 2014, there have been positive anomalies in all regions, with a trend that started in 2013 in the CLS for nitrate, phosphate, and silicate. Positive anomalies continued until 2018, where negative anomalies have since been observed on HB and CLS. In contrast on the GS, silicate concentrations rebounded in 2022-2023, and nitrate and phosphate fluctuated between positive and negative anomalies. Chl-a concentrations have followed an inverse pattern, with lower than normal concentrations for all three regions since 2014, except for the anomalously high concentration in 2015, and high concentrations on HB and CLS in 2022-2023. The high anomalies in 2015 and 2022 were associated with an intense phytoplankton bloom consisting mainly of *Phaeocystis sp.* which was identified from shipboard observations. Ocean color metrics (spring peak timing, fall bloom initiation, and annual and seasonal averages) showed no obvious trends over time and each region revealed its own pattern. Satellite observations are impacted by cloud cover, resulting in data gaps which might miss the peak of the bloom in a given year and region. Recurrent earlier sampling dates from year to year may partly explain the observed negative anomalies in in-situ chl-a concentrations, since sampling may have occurred before the start of the seasonal spring bloom.  

With the exception of *Pseudocalanus spp.* and Amphipoda, which exhibited high and low abundance anomalies respectively, other taxa do not show clear trends during the 2019-2023 period. In HB and CLS, the higher than average %PDI in *C. finmarchicus* may have been linked in part to their seasonal life-cycle where the populations were consistently more advanced in development than the average. The GS region, generally sampled later in the bloom season, showed a population growth rate which was slower or close to the average.  






[EDIT BELOW]

The  chemistry and biology of the Labrador Sea shows strong regional and interannual variation. The time period of 2019 to 2023 was marked by a steady decrease in pH with an increase in SF6 abundance. Furthermore, there was a shift in nutrients and chl-a, with a decline in nutrient concentrations, but an increase in chl-a. The spring bloom timing was highly variable, with implications for the zooplankton abundance. As our ocean continue to experience shifts in mean oceanographic conditions, long running time series are critical to understand the wide ranging impacts on ocean ecosystems.








# Acknowledgements

The authors thank the sea-going staff of the Bedford Institute of Oceanography and the officers and crew of the Canadian Coast Guard ships Amundsen and Captain Jacques Cartier as well as the UNOLS research vessel Atlantis. Jay Barthelotte, Robert Benjamin, Jay Bugden, Diana Cardoso, Carla Caverhill, Darlene Childs Terry Cormier, Melissa Falkner, Jennifer Field, Pascal Guillot, Adam Hartling, Dave Hebert, Flo Hum, Jeff Jackson, Matt Lawson, Chantelle Layton, Dave Levy, Richard Nelson, Kevin MacIsaac, Kevin Pauley, Tim Perry, Cathy Porter, Steve Punshon, Maddison Proudfoot, Peter Thamer Christiane Theriault, Mike Vining and Kristen Wilson contributed to sample collection, sample analysis, data analysis, data management, and data sharing.  


\clearpage

# References

<div id="refs"></div>
