---
title: |
  "Optical, Chemical, and Biological Oceanographic Conditions in the Labrador Sea from summer 2019 and 2023"
french_title: Titre ici (*Nom latin de l'espèce*)
year: 2025
report_number: nnn
author: |
  Marc Ringuette^1^,
  Emmanuel Devred^1^,
  Kumiko Azetsu-Scott^1^,
  Carrie-Ellen Gabriel^1^, and
  Stephanie Clay^1^
author_list: "Ringuette, M., Devred, E., Azetsu-Scott, K., Gabriel, C.-E., and Clay, S."
region: Maritimes Region
french_region: ""
isbn: ""
address: |
  ^1^Bedford Institute of Oceanography\
     Fisheries and Oceans Canada, 1 Challenger Drive\
     Dartmouth, Nova Scotia, B2Y 4A2, Canada\
french_address: ""
phone: "(555) 555-5555"
author_footnote: "Email: Marc.Ringuette@dfo-mpo.gc.ca | telephone: (555) 555-5555"
abstract: |
  The chemistry and biology of the Labrador Sea and adjacent shelves have undergone significant changes over the 2019–2023 period compared to previous years. The Atlantic Zonal Off-shelf Monitoring Program (AZOMP) revealed an increase in dissolved inorganic carbon and a decrease in pH, a trend that extends back to the beginning of the monitoring program in the mid-1990’s. While the mean concentration of chlorofluorocarbon (CFC-12) over the water column has remained stable, the concentration of sulfur hexafluoride ($SF_6$) has been increasing steadily since we began to measure it in 2011, reflecting the atmospheric history of these gases. The mean temperature of the top layer (0–100 m) has been mainly below normal since 2011, except for the Hamilton Bank where two warmer-than-normal years were observed in 2015 and 2018, and in the Central Labrador Sea when mean temperature was above normal in 2012. In 2019, the entire Labrador Sea temperature was above normal with a record-high mean temperature in the Central Labrador Sea largely explained by a delayed mission (June rather than May), while mean temperature was below normal in 2022. The shelves mean temperature were close to normal in 2023 and the Central Labrador Sea temperature was above-normal. In the 2019-2023 period, both surface and deep nutrients levels were below normal except for the Greenland Shelf in 2022 and surface silicate in 2023, however, the timing of the mission with respect to the spring phytoplankton bloom development may impacts the nutrient budget. In fact, the timing of the mission before 2019 occurred earlier each year compared to the previous year due to the constraints of crew change, and consistent dates in sea-going expeditions are needed to remove uncertainties related to sampling time. Deep nutrients exhibited inter-annual and regional variations until 2018. In recent years (2019-2023), deep-nutrients have remained below average in all three regions of interest, suggesting a profound change in the biogeochemistry of the Labrador Sea.  
  
  While integrated chlorophyll-a levels were below normal in 2019, continuing a trend that started in 2014, except in 2015 in the Central Labrador Sea, values in 2022 and 2023 were above average, with a record-high integrated chlorophyll-a value in 2022 on the Hamilton Bank. An unusually large bloom of *Phaeocystis sp.*, that covered a large extent of the Labrador Sea, occurred in 2022 and explains the high values. This is the second largest Phaeocystis sp. bloom event in the Labrador Sea after 2015. Satellite-derived chlorophyll-a concentration reveals the large variability in the peak timing of the spring bloom and in the fall bloom initiation. While the mean annual satellite-derived chlorophyll-a on Hamilton Bank was mainly above-normal, values were below-normal between 2019-2021 on the Greenland Shelf and Central Labrador Sea, and above normal in 2022-2023.  
  
  Unfortunately, the late (2020) or lack of (2021) in situ data collection due to the COVID pandemic and the lack of ship availability, respectively, did not allow inclusion of these two years in the current report with the exception of satellite ocean color metrics, such that recent in situ trends need to be interpreted with caution. 

french_abstract: |
    La chimie et la biologie de la mer du Labrador et des plateaux adjacents ont subi des changements importants au cours de la période 2019-2023 par rapport aux années précédentes. Le Programme de monitorage de la zone hauturière Atlantique (PMZAO) a révélé une augmentation du carbone inorganique dissous et une diminution du pH, une tendance qui continue depuis le début du programme de monitorage au milieu des années 1990. Alors que la concentration moyenne de chlorofluorocarbone (CFC-12) dans la colonne d'eau est restée stable, la concentration d'hexafluorure de soufre (SF6) a augmenté régulièrement depuis le commencement des mesures en 2011, reflétant l'histoire atmosphérique de ces gaz. La température moyenne de la couche supérieure (0-100 m) est principalement inférieure à la normale depuis 2011, à l'exception du banc de Hamilton où deux années plus chaudes que la normale ont été observées en 2015 et 2018, et dans le centre de la mer du Labrador où la température moyenne était supérieure à la normale en 2012.  En 2019, la température de l'ensemble de la mer du Labrador  était supérieure à la normale, avec une température moyenne record dans le centre de la mer du Labrador largement expliquée par une mission tardive (Juin plutôt que May) , tandis que la température moyenne était inférieure à la normale en 2022. En 2023, la température moyenne des plateaux était proche de la normale et celle du centre de la mer du Labrador était supérieure à la normale. Au cours de la période 2019-2023, les niveaux de nutriments en surface et en profondeur étaient inférieurs à la normale, à l'exception du plateau continental du Groënland en 2022 et du silicate en surface en 2023, mais la date de la mission par rapport au développement de l'efflorescence phytoplanctonique au printemps peut avoir une incidence sur le bilan des nutriments. En fait, la date de la mission avant 2019 a été avancé chaque année par rapport à l'année précédente en raison des contraintes liées au changement d'équipage, alors que des dates de mission constantes sont nécessaires pour éliminer les incertitudes liées à la date de l'échantillonnage. Les nutriments profonds ont présenté des variations interannuelles et régionales jusqu'en 2018. Au cours des dernières années (2019-2023), les nutriments profonds sont restés inférieurs à la moyenne dans les trois régions concernées, ce qui suggère un changement profond dans la biogéochimie de la mer du Labrador.  

    Alors que les niveaux intégrés de chlorophylle-a étaient inférieurs à la normale en 2019, poursuivant une tendance amorcée en 2014, sauf en 2015 dans le centre de la mer du Labrador, les valeurs en 2022 et 2023 étaient supérieures à la moyenne, avec une valeur intégrée de chlorophylle-a record en 2022 sur le banc de Hamilton. Une floraison inhabituellement importante de Phaeocystis sp. qui a couvert une grande partie de la mer du Labrador s'est produite en 2022 et explique ces valeurs élevées. Il s'agit de la deuxième plus grande efflorescence de Phaeocystis sp. dans la mer du Labrador après celle de 2015. La concentration de chlorophylle-a dérivée du satellite révèle la grande variabilité de la période du maximum de l'efflorescence printanière et de l'initiation de l'efflorescence automnale. Alors que la moyenne annuelle de la chlorophylle-a dérivée du satellite sur le banc de Hamilton était principalement supérieure à la normale, les valeurs étaient inférieures à la normale entre 2019 et 2021 sur le plateau continental du Groënland et dans la partie centrale de la mer du Labrador, et supérieures à la normale en 2022-2023.  

    Malheureusement, la collecte tardive (2020) ou l'absence (2021) de données in situ respectivement en raison de la pandémie de COVID et du manque de disponibilité de navires n'a pas permis d'inclure ces deux années dans le présent rapport à l'exception des mesures de la couleur de l'océan obtenues par satellite.  L’observation des tendances in situ récentes doivent donc être interprétées avec prudence.  

# `show_continued_text` is a logical which, if `true`, places
# "Continued on the next page..." and "...Continued from the previous page" or
# the french equivalents (if `french` = `true`) on all long tables created
# with `csas_table()` that cross page boundaries. If `false`, these will
# both be absent from all tables. If it is missing or any other value than
# `false`, it will be assumed to be `true`
citation_french: "Ringuette, M., Devred, E., Azetsu-Scott, K., Gabriel, C.-E., and Clay, S. 2025. Conditions océanographiques optiques, chimiques, et biologiques dans la mer du Labrador de 2019 à 2023.  Rap. Tech. can. Sci. Halieut. Aquat. nnn: vi + 30 p."
show_continued_text: true
output:
 csasdown::techreport_pdf:
   french: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: true
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: false
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: false
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: false
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) csasdown::render())
site: bookdown::bookdown_site
link-citations: true
bibliography: ../refs.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
# define paths to different products (subdirectories in these should be data/ and figures/[report_year])
report_year <- 2023
path_common <- "../../analysis/common/"
path_stationMap <- "../../analysis/stationMap/"
path_cruiseAndBloomTiming <- "../../analysis/cruiseAndBloomTimingPlot/"
path_oceanAcidification <- "../../analysis/inSituOceanAcidification/"
path_tracers <- "../../analysis/inSituTracers/"
path_temperatureScorecard <- "../../analysis/inSituTemperatureScorecard/"
path_nutrientsScorecards <- "../../analysis/inSituNutrientsScorecards/"
path_chlaScorecard <- "../../analysis/inSituChlaScorecard/"
path_satelliteOceanColour <- "../../analysis/satelliteOceanColour/"
path_mesozooplanktonScorecards <- "../../analysis/inSituMesozooplanktonScorecards/"
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
library(kableExtra)
```
